import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React from 'react';
import NavBar from '@wrap-dapps/components/navbar/NavBarComponent';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the Jungle</h1>
      </main>
    </div>
  );
}
